Init frontend
union-platform/union-app pull request #9
Opened 2021-07-16 20:27 UTC by rexolion

## Description
Init React/Typescript Project for Union + eslint.

## Related issue(s)
None

## :white_check_mark: Checklist for your Pull Request

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
    - Haddock

- Public contracts
  - [x] My changes doesn't break any Licenses.
  - [ ] I added an entry to the [changelog](../tree/master/CHANGES.md) if my changes are visible to the users
        and
  - [ ] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Union](https://github.com/union-platform/guides/blob/master/commits.md).
- [x] My code complies with the [styles guide](https://github.com/union-platform/guides/blob/master/README.md#programming-languages).

2021-07-17 06:41 UTC, worm2fed requested changes
Also - please add license identifiers to all your files

2021-07-17 06:41 UTC, worm2fed commented on frontend/.gitignore
> +/node_modules
this is a file, isn't it?
and in this file upper we've already have `node_modules/`

2021-07-17 06:41 UTC, worm2fed commented on frontend/.gitignore
> +.pnp.js
```
/.pnp
.pnp.js
```

why not `.pnp*`?

2021-07-17 06:41 UTC, worm2fed commented on frontend/.gitignore
> +/coverage
if it's a directory, it should be `coverage/`

2021-07-17 06:41 UTC, worm2fed commented on frontend/.gitignore
> +/build
same

2021-07-17 06:41 UTC, worm2fed commented on frontend/.gitignore
> +.DS_Store
please, do not add your OS specific files, to ignore it - add to your global OS gitignore

2021-07-17 06:41 UTC, worm2fed commented on frontend/.gitignore
> +.env.production.local
`.env.*.local`?

2021-07-17 06:41 UTC, worm2fed commented on frontend/.gitignore
> +npm-debug.log*
`*.log*`

2021-07-17 06:41 UTC, worm2fed commented on frontend/package.json
> +  "name": "union_frontend",
let's name it `union-app`? what do you think?

2021-07-17 06:41 UTC, worm2fed commented on frontend/package.json
> +  "version": "0.1.0",
Is haskell there are practice to set `0.0.0` until package is released and then, for first release set `0.1.0` (or smth)
Is it same for frontend staff?

2021-07-17 06:41 UTC, worm2fed commented on frontend/public/index.html
> +    <title>React App</title>
Please, set real title here, for example `Union` or `Union Platform`

2021-07-17 06:41 UTC, worm2fed commented on frontend/public/index.html
> +      content="Web site created using create-react-app"
Please, set real description here

2021-07-17 06:41 UTC, worm2fed commented on frontend/public/robots.txt
> +Disallow:
do we want to disallow robots parse Union? I guess it's cool to show our app in search engines

2021-07-17 06:43 UTC, worm2fed commented
and for your future PRs
Please, set branch name as described in our policy
instead of `init_frontend` it should be `rexolion/init_frontend`, and in case it would have issue associated with your pr, it should be `rexolion/#420-init_frontend`

2021-08-08 13:00 UTC, rexolion commented on frontend/public/robots.txt
> +Disallow:
Actually "Disallow: " (empty) means "Allow all", disallow all — "Disallow: /" — https://www.robotstxt.org/robotstxt.html

2021-08-09 06:48 UTC, worm2fed commented on frontend/.reuse/dep5
> +Files: *
Since you've added licence identifiers to frontend files, I think you do not need this `/frontend/.reuse/` dir any more)

2021-08-09 07:17 UTC, worm2fed approved these changes
It's good now.
But please, squash your commits and add appropreate body to first one, like here: https://github.com/union-platform/guides/blob/master/commits.md#commit-messages (point 4)

2022-01-07 20:15 UTC, worm2fed approved these changes

2022-01-07 20:24 UTC, merged